### ISSUE TITLE
Git tags point to wrong commits

### ISSUE THREAD

**Issue by ryandesign** [newville/ifeffit#6]
This git repository contains three tags: 1.2.final, 1.2.12, and 1.2.13. They all point to the same commit which seems wrong. They all point to the latest commit in this repository (83b3455b7b0bfc5d2a0ea7da2c5e9ab761d4a772) which seems wrong. I see no evidence that a version 1.2.13 ever existed given that files src/lib/sys.h, src/win32/sys.h, src/win32/lib_Makefile, and ChangeLog all state the version is 1.2.12.

**Comment by newville** [comment]
@ryandesign sorry, but not worth discussing.
